name: Java CI with Maven
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout Alexandria
      uses: actions/checkout@v2
      with:
        repository: g2forge/alexandria
        path: alexandria
    - name: Build Alexandria
      working-directory: ./alexandria
      run: mvn -B install --file pom.xml -P release -DskipTests -Dgpg.skip
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: habitat
    - name: Build with Maven
      working-directory: ./habitat
      run: mvn -B package --file pom.xml -P release -Dgpg.skip